on: 
  push:
    branches: [ master ]
jobs:
  my-job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: "run the action"
      id: hello
      uses: ./
      with:
        myInput: "Man"
     - name: output the memory
       run: |
         echo ${{ steps.hello.outputs.memory }}
         echo "Fuck You All Successfully"
        
